{
 "title": "SLO Compliance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ALERTS{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLO Status - Node 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:availability:ratio{node_id=\"node-2\"} * 100",
     "legendFormat": "Node 2 availability"
    },
    {
     "expr": "node:response_time:p95{node_id=\"node-2\"}",
     "legendFormat": "Node 2 Response time"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(oracle_request_duration_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node:availability:ratio * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Budget Remaining (%)",
   "type": "gauge",
   "description": "This calculates how much of your 0.1% error budget remains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (1 - node:availability:ratio) / 0.001) * 100, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Status - Node 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:availability:ratio{node_id=\"node-1\"} * 100",
     "legendFormat": "Node 1 availability"
    },
    {
     "expr": "node:response_time:p95{node_id=\"node-1\"}",
     "legendFormat": "Node 1 Response time"
    }
   ]
  },
  {
   "title": "SLO Status - Node 3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:availability:ratio{node_id=\"node-3\"} * 100",
     "legendFormat": "Node 3 availability"
    },
    {
     "expr": "node:response_time:p95{node_id=\"node-3\"}",
     "legendFormat": "Node 3 Response time"
    }
   ]
  }
 ]
}